<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWCVsR46\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWCVsR46/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWCVsR46.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWCVsR46\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWCVsR46\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WCVsR46',
    'container.build_id' => '7e0be5ad',
    'container.build_time' => 1562575570,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWCVsR46');
