<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_twig_error_test' => [['code', '_format'], ['_controller' => 'twig.controller.preview_error::previewErrorPageAction', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception::showAction'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception::cssAction'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    ' hello_index' => [[], ['_controller' => 'App\\Controller\\HomeController::helloWorld'], [], [['text', '/hello']], [], []],
    'firstName_index' => [[], ['_controller' => 'App\\Controller\\HomeController::first_name'], [], [['text', '/firstName']], [], []],
    'your_age_index' => [[], ['_controller' => 'App\\Controller\\HomeController::majeur'], [], [['text', '/majeur']], [], []],
    'numero_de_page' => [['page'], ['_controller' => 'App\\Controller\\HomeController::list'], [], [['variable', '/', '[^/]++', 'page', true], ['text', '/list']], [], []],
    'adress' => [[], ['_controller' => 'App\\Controller\\HomeController::adress'], [], [['text', '/adress']], [], []],
    'twig' => [[], ['_controller' => 'App\\Controller\\HomeController::twigBasic'], [], [['text', '/twig']], [], []],
    'homePage' => [[], ['_controller' => 'App\\Controller\\HomeController::homePage'], [], [['text', '/homePage']], [], []],
    'showArticle' => [[], ['_controller' => 'App\\Controller\\HomeController::showArticle'], [], [['text', '/showArticle']], [], []],
    'exo01' => [[], ['_controller' => 'App\\Controller\\HomeController::exo01'], [], [['text', '/exo01']], [], []],
    'exo02' => [[], ['_controller' => 'App\\Controller\\HomeController::exo02'], [], [['text', '/exo02']], [], []],
    'exo03' => [[], ['_controller' => 'App\\Controller\\HomeController::exo03'], [], [['text', '/exo03']], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\HomeController::contact'], [], [['text', '/contact']], [], []],
];
